services:
  crud:
    container_name: crud
    build:
      context: .
      dockerfile: DockerFile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      # - ./:/app
      - ./images:/app/images
      - /app/node_modules
    env_file: ".env"
    depends_on:
      - db.my
      - redis.my
  db.my:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  redis.my:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - "6379:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "test"
    environment:
      - REDIS_PASSWORD=test
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - crud
      - db.my
      - redis.my