FROM node:20-alpine

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/

COPY . .

RUN npm install

RUN npm run build

ENV HOST 0.0.0.0

CMD [ "node", ".output/server/index.mjs" ]


# dev
# FROM node:20-alpine

# WORKDIR /app

# COPY package.json /app/
# COPY package-lock.json /app/

# RUN npm install

# ENV HOST 0.0.0.0

# CMD [ "npm", "run", "dev" ]